<?php

session_start();
include '../../../config/db.php';

try {
    $deptID = trim($_SESSION['deptID']);
    $deptCode = trim($_SESSION['deptCode']);
    $roleID = trim($_SESSION['roleID']);
    $orgID = $_GET['orgID'];

    if ($orgID == "all") {
        $sql = "SELECT DISTINCT dbo.HREMP.HREMP_EMPCODE, dbo.HREMP.HREMP_FNAME, dbo.HREMP.HREMP_LNAME, dbo.ASORG.ASORG_ORGNAME, dbo.HRJOB.HRJOB_JOBNAME, dbo.HREMP.HREMP_PHONEC, dbo.HREMP.HREMP_NATION, dbo.HREMP.HREMP_LANGUAGE, dbo.HREMP.HREMP_SSN, dbo.FILEINDEX.FILENAME, CONCAT ( HREMP_STATE, ' ', HREMP_ADDRH1 ) AS ADDRESS, CONVERT (DATE, HREMP_HIREDAY) AS HREMP_HIREDAY, CASE WHEN HREMP_MSTATUS = '1' THEN 'Single' ELSE 'Married' END AS MSTATUS, dbo.View_Nation.ASSCODE_DESCRIP FROM dbo.HREMP LEFT JOIN dbo.HRJOB ON dbo.HREMP.HREMP_JOBID = HRJOB_JOBID AND dbo.HREMP.HREMP_DEPT = dbo.HRJOB.HRJOB_DEPT LEFT JOIN dbo.ASORG ON dbo.HREMP.HREMP_ORG = ASORG_ORGID AND dbo.HREMP.HREMP_ORG = dbo.ASORG.ASORG_ORGID LEFT JOIN dbo.HREMPEDU ON dbo.HREMP.HREMP_EMPCODE = HREMPEDU_EMPID AND dbo.HREMP.HREMP_EMPCODE = dbo.HREMPEDU.HREMPEDU_EMPID LEFT JOIN dbo.FILEINDEX ON dbo.HREMP.HREMP_FILEID = dbo.FILEINDEX.FILEID LEFT JOIN dbo.View_Nation ON dbo.HREMP.HREMP_NATION = dbo.View_Nation.ASSCODE_VALUE WHERE dbo.HREMP.HREMP_STATUS = 1";
    } else {
        $sql = "SELECT DISTINCT dbo.HREMP.HREMP_EMPCODE, dbo.HREMP.HREMP_FNAME, dbo.HREMP.HREMP_LNAME, dbo.ASORG.ASORG_ORGNAME, dbo.HRJOB.HRJOB_JOBNAME, dbo.HREMP.HREMP_PHONEC, dbo.HREMP.HREMP_NATION, dbo.HREMP.HREMP_LANGUAGE, dbo.HREMP.HREMP_SSN, dbo.FILEINDEX.FILENAME, CONCAT ( HREMP_STATE, ' ', HREMP_ADDRH1 ) AS ADDRESS, CONVERT (DATE, HREMP_HIREDAY) AS HREMP_HIREDAY, CASE WHEN HREMP_MSTATUS = '1' THEN 'Single' ELSE 'Married' END AS MSTATUS, dbo.View_Nation.ASSCODE_DESCRIP FROM dbo.HREMP LEFT JOIN dbo.HRJOB ON dbo.HREMP.HREMP_JOBID = HRJOB_JOBID AND dbo.HREMP.HREMP_DEPT = dbo.HRJOB.HRJOB_DEPT LEFT JOIN dbo.ASORG ON dbo.HREMP.HREMP_ORG = ASORG_ORGID AND dbo.HREMP.HREMP_ORG = dbo.ASORG.ASORG_ORGID LEFT JOIN dbo.HREMPEDU ON dbo.HREMP.HREMP_EMPCODE = HREMPEDU_EMPID AND dbo.HREMP.HREMP_EMPCODE = dbo.HREMPEDU.HREMPEDU_EMPID LEFT JOIN dbo.FILEINDEX ON dbo.HREMP.HREMP_FILEID = dbo.FILEINDEX.FILEID LEFT JOIN dbo.View_Nation ON dbo.HREMP.HREMP_NATION = dbo.View_Nation.ASSCODE_VALUE WHERE HREMP_ORG = '{$orgID}' AND HREMP_STATUS = '1'";
    }
    $stmt = $psa_connect->prepare($sql);
    $stmt->execute();

    $dataArray = array();

    while ($row = $stmt->fetch(PDO::FETCH_ASSOC)) {
        $dataArray[] = $row;
    }

    echo json_encode($dataArray);
} catch (PDOException $e) {
    echo $e->getMessage();
}
$psa_connect = NULL;
