<?php

session_start();
include '../../../config/db.php';

try {
    $deptID = trim($_SESSION['deptID']);
    $deptCode = trim($_SESSION['deptCode']);
    $roleID = trim($_SESSION['roleID']);
    $orgID = $_GET['orgID'];

    if ($orgID == "all") {
        $sql = "SELECT DISTINCT HREMP_EMPCODE, HREMP_FNAME, HREMP_LNAME, ASORG_ORGNAME, HRJOB_JOBNAME, HREMP_PHONEC, HREMP_NATION, HREMP_LANGUAGE, HREMP_SSN, FILENAME, CONCAT ( HREMP_STATE, ' ', HREMP_ADDRH1 ) AS [ADDRESS], CONVERT (DATE, HREMP_HIREDAY) [HREMP_HIREDAY], CASE WHEN HREMP_MSTATUS = '1' THEN 'Single' ELSE 'Married' END AS [MSTATUS], HREMPEDU_SCHOOL ASSCODE_DESCRIP FROM dbo.HREMP LEFT JOIN dbo.HRJOB ON dbo.HREMP.HREMP_JOBID = HRJOB_JOBID AND dbo.HREMP.HREMP_DEPT = dbo.HRJOB.HRJOB_DEPT LEFT JOIN dbo.ASORG ON dbo.HREMP.HREMP_ORG = ASORG_ORGID AND dbo.HREMP.HREMP_ORG = dbo.ASORG.ASORG_ORGID LEFT JOIN dbo.HREMPEDU ON dbo.HREMP.HREMP_EMPCODE = HREMPEDU_EMPID AND dbo.HREMP.HREMP_EMPCODE = dbo.HREMPEDU.HREMPEDU_EMPID LEFT JOIN dbo.ASSCODE ON dbo.HREMP.HREMP_NATION = ASSCODE_VALUE LEFT JOIN dbo.FILEINDEX ON dbo.HREMP.HREMP_FILEID = dbo.FILEINDEX.FILEID WHERE HREMP_STATUS = 1";
    } else {
        $sql = "SELECT DISTINCT HREMP_EMPCODE, HREMP_FNAME, HREMP_LNAME, ASORG_ORGNAME, HRJOB_JOBNAME, HREMP_PHONEC, HREMP_NATION, HREMP_LANGUAGE, HREMP_SSN, FILENAME, CONCAT ( HREMP_STATE, ' ', HREMP_ADDRH1 ) AS [ADDRESS], CONVERT (DATE, HREMP_HIREDAY) [HREMP_HIREDAY], CASE WHEN HREMP_MSTATUS = '1' THEN 'Single' ELSE 'Married' END AS [MSTATUS], HREMPEDU_SCHOOL ASSCODE_DESCRIP FROM dbo.HREMP LEFT JOIN dbo.HRJOB ON dbo.HREMP.HREMP_JOBID = HRJOB_JOBID AND dbo.HREMP.HREMP_DEPT = dbo.HRJOB.HRJOB_DEPT LEFT JOIN dbo.ASORG ON dbo.HREMP.HREMP_ORG = ASORG_ORGID AND dbo.HREMP.HREMP_ORG = dbo.ASORG.ASORG_ORGID LEFT JOIN dbo.HREMPEDU ON dbo.HREMP.HREMP_EMPCODE = HREMPEDU_EMPID AND dbo.HREMP.HREMP_EMPCODE = dbo.HREMPEDU.HREMPEDU_EMPID LEFT JOIN dbo.ASSCODE ON dbo.HREMP.HREMP_NATION = ASSCODE_VALUE LEFT JOIN dbo.FILEINDEX ON dbo.HREMP.HREMP_FILEID = dbo.FILEINDEX.FILEID  WHERE HREMP_ORG = '{$orgID}' AND HREMP_STATUS = '1'";
    }
    $stmt = $psa_connect->prepare($sql);
    $stmt->execute();

    $dataArray = array();

    while ($row = $stmt->fetch(PDO::FETCH_ASSOC)) {
        $dataArray[] = $row;
    }

    echo json_encode($dataArray);
} catch (PDOException $e) {
    echo $e->getMessage();
}
$psa_connect = NULL;
