<?php

include '../../../config/db.php';

try {
    $org = $_GET['org'];
    $fromDate = $_GET['fromDate'];
    $toDate = $_GET['toDate'];

    $sql = "WITH cte AS(SELECT 
            emp.HREMP_EMPCODE AS [EmpCode], 
            emp.HREMP_FNAME +' '+HREMP_LNAME AS [EmpName],
            CONVERT(DATE, emp.HREMP_HIREDAY) AS [Hireday],
            job.HRJOB_JOBNAME AS [Position],
            org.ASORG_ORGNAME AS [Dept],
            ISNULL((SELECT SUM( CASE WHEN CONVERT(DATE, '{$fromDate}') > CONVERT(DATE, LVLEAVEREQ_BDATE) THEN DATEDIFF(DAY, CONVERT(DATE, '{$fromDate}'), CONVERT(DATE, LVLEAVEREQ_EDATE)) + 1 WHEN CONVERT(DATE, '{$toDate}') < CONVERT(DATE, LVLEAVEREQ_EDATE) THEN DATEDIFF(DAY, CONVERT(DATE, LVLEAVEREQ_BDATE), CONVERT(DATE, '{$toDate}')) + 1 ELSE DATEDIFF(DAY, CONVERT(DATE, LVLEAVEREQ_BDATE), CONVERT(DATE, LVLEAVEREQ_EDATE)) + 1 END) FROM [PSA66].[dbo].[LVLEAVEREQ] WHERE [LVLEAVEREQ_EMPID] = HREMP_EMPID AND (CONVERT(DATE, LVLEAVEREQ_BDATE) BETWEEN '{$fromDate}' AND '{$toDate}') AND LVLEAVEREQ_LEAVECODE = 'AB' AND LVLEAVEREQ_STATUS NOT IN ('0', '3', '4') ), 0) AS [AB],
            ISNULL((SELECT SUM( CASE WHEN CONVERT(DATE, '{$fromDate}') > CONVERT(DATE, LVLEAVEREQ_BDATE) THEN DATEDIFF(DAY, CONVERT(DATE, '{$fromDate}'), CONVERT(DATE, LVLEAVEREQ_EDATE)) + 1 WHEN CONVERT(DATE, '{$toDate}') < CONVERT(DATE, LVLEAVEREQ_EDATE) THEN DATEDIFF(DAY, CONVERT(DATE, LVLEAVEREQ_BDATE), CONVERT(DATE, '{$toDate}')) + 1 ELSE DATEDIFF(DAY, CONVERT(DATE, LVLEAVEREQ_BDATE), CONVERT(DATE, LVLEAVEREQ_EDATE)) + 1 END) FROM [PSA66].[dbo].[LVLEAVEREQ] WHERE [LVLEAVEREQ_EMPID] = HREMP_EMPID AND (CONVERT(DATE, LVLEAVEREQ_BDATE) BETWEEN '{$fromDate}' AND '{$toDate}') AND LVLEAVEREQ_LEAVECODE = 'AL' AND LVLEAVEREQ_STATUS NOT IN ('0', '3', '4') ), 0) AS [AL],
            ISNULL((SELECT SUM( CASE WHEN CONVERT(DATE, '{$fromDate}') > CONVERT(DATE, LVLEAVEREQ_BDATE) THEN DATEDIFF(DAY, CONVERT(DATE, '{$fromDate}'), CONVERT(DATE, LVLEAVEREQ_EDATE)) + 1 WHEN CONVERT(DATE, '{$toDate}') < CONVERT(DATE, LVLEAVEREQ_EDATE) THEN DATEDIFF(DAY, CONVERT(DATE, LVLEAVEREQ_BDATE), CONVERT(DATE, '{$toDate}')) + 1 ELSE DATEDIFF(DAY, CONVERT(DATE, LVLEAVEREQ_BDATE), CONVERT(DATE, LVLEAVEREQ_EDATE)) + 1 END) FROM [PSA66].[dbo].[LVLEAVEREQ] WHERE [LVLEAVEREQ_EMPID] = HREMP_EMPID AND (CONVERT(DATE, LVLEAVEREQ_BDATE) BETWEEN '{$fromDate}' AND '{$toDate}') AND LVLEAVEREQ_LEAVECODE = 'FL' AND LVLEAVEREQ_STATUS NOT IN ('0', '3', '4') ), 0) AS [FL],
            ISNULL((SELECT SUM( CASE WHEN CONVERT(DATE, '{$fromDate}') > CONVERT(DATE, LVLEAVEREQ_BDATE) THEN DATEDIFF(DAY, CONVERT(DATE, '{$fromDate}'), CONVERT(DATE, LVLEAVEREQ_EDATE)) + 1 WHEN CONVERT(DATE, '{$toDate}') < CONVERT(DATE, LVLEAVEREQ_EDATE) THEN DATEDIFF(DAY, CONVERT(DATE, LVLEAVEREQ_BDATE), CONVERT(DATE, '{$toDate}')) + 1 ELSE DATEDIFF(DAY, CONVERT(DATE, LVLEAVEREQ_BDATE), CONVERT(DATE, LVLEAVEREQ_EDATE)) + 1 END) FROM [PSA66].[dbo].[LVLEAVEREQ] WHERE [LVLEAVEREQ_EMPID] = HREMP_EMPID AND (CONVERT(DATE, LVLEAVEREQ_BDATE) BETWEEN '{$fromDate}' AND '{$toDate}') AND LVLEAVEREQ_LEAVECODE = 'HL' AND LVLEAVEREQ_STATUS NOT IN ('0', '3', '4') ), 0) AS [HL],
            ISNULL((SELECT SUM( CASE WHEN CONVERT(DATE, '{$fromDate}') > CONVERT(DATE, LVLEAVEREQ_BDATE) THEN DATEDIFF(DAY, CONVERT(DATE, '{$fromDate}'), CONVERT(DATE, LVLEAVEREQ_EDATE)) + 1 WHEN CONVERT(DATE, '{$toDate}') < CONVERT(DATE, LVLEAVEREQ_EDATE) THEN DATEDIFF(DAY, CONVERT(DATE, LVLEAVEREQ_BDATE), CONVERT(DATE, '{$toDate}')) + 1 ELSE DATEDIFF(DAY, CONVERT(DATE, LVLEAVEREQ_BDATE), CONVERT(DATE, LVLEAVEREQ_EDATE)) + 1 END) FROM [PSA66].[dbo].[LVLEAVEREQ] WHERE [LVLEAVEREQ_EMPID] = HREMP_EMPID AND (CONVERT(DATE, LVLEAVEREQ_BDATE) BETWEEN '{$fromDate}' AND '{$toDate}') AND LVLEAVEREQ_LEAVECODE = 'ML' AND LVLEAVEREQ_STATUS NOT IN ('0', '3', '4') ), 0) AS [ML],
            ISNULL((SELECT SUM( CASE WHEN CONVERT(DATE, '{$fromDate}') > CONVERT(DATE, LVLEAVEREQ_BDATE) THEN DATEDIFF(DAY, CONVERT(DATE, '{$fromDate}'), CONVERT(DATE, LVLEAVEREQ_EDATE)) + 1 WHEN CONVERT(DATE, '{$toDate}') < CONVERT(DATE, LVLEAVEREQ_EDATE) THEN DATEDIFF(DAY, CONVERT(DATE, LVLEAVEREQ_BDATE), CONVERT(DATE, '{$toDate}')) + 1 ELSE DATEDIFF(DAY, CONVERT(DATE, LVLEAVEREQ_BDATE), CONVERT(DATE, LVLEAVEREQ_EDATE)) + 1 END) FROM [PSA66].[dbo].[LVLEAVEREQ] WHERE [LVLEAVEREQ_EMPID] = HREMP_EMPID AND (CONVERT(DATE, LVLEAVEREQ_BDATE) BETWEEN '{$fromDate}' AND '{$toDate}') AND LVLEAVEREQ_LEAVECODE = 'NDL' AND LVLEAVEREQ_STATUS NOT IN ('0', '3', '4') ), 0) AS [NDL],
            ISNULL((SELECT SUM( CASE WHEN CONVERT(DATE, '{$fromDate}') > CONVERT(DATE, LVLEAVEREQ_BDATE) THEN DATEDIFF(DAY, CONVERT(DATE, '{$fromDate}'), CONVERT(DATE, LVLEAVEREQ_EDATE)) + 1 WHEN CONVERT(DATE, '{$toDate}') < CONVERT(DATE, LVLEAVEREQ_EDATE) THEN DATEDIFF(DAY, CONVERT(DATE, LVLEAVEREQ_BDATE), CONVERT(DATE, '{$toDate}')) + 1 ELSE DATEDIFF(DAY, CONVERT(DATE, LVLEAVEREQ_BDATE), CONVERT(DATE, LVLEAVEREQ_EDATE)) + 1 END) FROM [PSA66].[dbo].[LVLEAVEREQ] WHERE [LVLEAVEREQ_EMPID] = HREMP_EMPID AND (CONVERT(DATE, LVLEAVEREQ_BDATE) BETWEEN '{$fromDate}' AND '{$toDate}') AND LVLEAVEREQ_LEAVECODE = 'PH' AND LVLEAVEREQ_STATUS NOT IN ('0', '3', '4') ), 0) AS [PH],
            ISNULL((SELECT SUM( CASE WHEN CONVERT(DATE, '{$fromDate}') > CONVERT(DATE, LVLEAVEREQ_BDATE) THEN DATEDIFF(DAY, CONVERT(DATE, '{$fromDate}'), CONVERT(DATE, LVLEAVEREQ_EDATE)) + 1 WHEN CONVERT(DATE, '{$toDate}') < CONVERT(DATE, LVLEAVEREQ_EDATE) THEN DATEDIFF(DAY, CONVERT(DATE, LVLEAVEREQ_BDATE), CONVERT(DATE, '{$toDate}')) + 1 ELSE DATEDIFF(DAY, CONVERT(DATE, LVLEAVEREQ_BDATE), CONVERT(DATE, LVLEAVEREQ_EDATE)) + 1 END) FROM [PSA66].[dbo].[LVLEAVEREQ] WHERE [LVLEAVEREQ_EMPID] = HREMP_EMPID AND (CONVERT(DATE, LVLEAVEREQ_BDATE) BETWEEN '{$fromDate}' AND '{$toDate}') AND LVLEAVEREQ_LEAVECODE = 'PL' AND LVLEAVEREQ_STATUS NOT IN ('0', '3', '4') ), 0) AS [PL],
            ISNULL((SELECT SUM( CASE WHEN CONVERT(DATE, '{$fromDate}') > CONVERT(DATE, LVLEAVEREQ_BDATE) THEN DATEDIFF(DAY, CONVERT(DATE, '{$fromDate}'), CONVERT(DATE, LVLEAVEREQ_EDATE)) + 1 WHEN CONVERT(DATE, '{$toDate}') < CONVERT(DATE, LVLEAVEREQ_EDATE) THEN DATEDIFF(DAY, CONVERT(DATE, LVLEAVEREQ_BDATE), CONVERT(DATE, '{$toDate}')) + 1 ELSE DATEDIFF(DAY, CONVERT(DATE, LVLEAVEREQ_BDATE), CONVERT(DATE, LVLEAVEREQ_EDATE)) + 1 END) FROM [PSA66].[dbo].[LVLEAVEREQ] WHERE [LVLEAVEREQ_EMPID] = HREMP_EMPID AND (CONVERT(DATE, LVLEAVEREQ_BDATE) BETWEEN '{$fromDate}' AND '{$toDate}') AND LVLEAVEREQ_LEAVECODE = 'SL' AND LVLEAVEREQ_STATUS NOT IN ('0', '3', '4') ), 0) AS [SL],
            ISNULL((SELECT SUM( CASE WHEN CONVERT(DATE, '{$fromDate}') > CONVERT(DATE, LVLEAVEREQ_BDATE) THEN DATEDIFF(DAY, CONVERT(DATE, '{$fromDate}'), CONVERT(DATE, LVLEAVEREQ_EDATE)) + 1 WHEN CONVERT(DATE, '{$toDate}') < CONVERT(DATE, LVLEAVEREQ_EDATE) THEN DATEDIFF(DAY, CONVERT(DATE, LVLEAVEREQ_BDATE), CONVERT(DATE, '{$toDate}')) + 1 ELSE DATEDIFF(DAY, CONVERT(DATE, LVLEAVEREQ_BDATE), CONVERT(DATE, LVLEAVEREQ_EDATE)) + 1 END) FROM [PSA66].[dbo].[LVLEAVEREQ] WHERE [LVLEAVEREQ_EMPID] = HREMP_EMPID AND (CONVERT(DATE, LVLEAVEREQ_BDATE) BETWEEN '{$fromDate}' AND '{$toDate}') AND LVLEAVEREQ_LEAVECODE = 'SPL' AND LVLEAVEREQ_STATUS NOT IN ('0', '3', '4') ), 0) AS [SPL],
            ISNULL((SELECT SUM( CASE WHEN CONVERT(DATE, '{$fromDate}') > CONVERT(DATE, LVLEAVEREQ_BDATE) THEN DATEDIFF(DAY, CONVERT(DATE, '{$fromDate}'), CONVERT(DATE, LVLEAVEREQ_EDATE)) + 1 WHEN CONVERT(DATE, '{$toDate}') < CONVERT(DATE, LVLEAVEREQ_EDATE) THEN DATEDIFF(DAY, CONVERT(DATE, LVLEAVEREQ_BDATE), CONVERT(DATE, '{$toDate}')) + 1 ELSE DATEDIFF(DAY, CONVERT(DATE, LVLEAVEREQ_BDATE), CONVERT(DATE, LVLEAVEREQ_EDATE)) + 1 END) FROM [PSA66].[dbo].[LVLEAVEREQ] WHERE [LVLEAVEREQ_EMPID] = HREMP_EMPID AND (CONVERT(DATE, LVLEAVEREQ_BDATE) BETWEEN '{$fromDate}' AND '{$toDate}') AND LVLEAVEREQ_LEAVECODE = 'TL' AND LVLEAVEREQ_STATUS NOT IN ('0', '3', '4') ), 0) AS [TL],
            ISNULL((SELECT SUM( CASE WHEN CONVERT(DATE, '{$fromDate}') > CONVERT(DATE, LVLEAVEREQ_BDATE) THEN DATEDIFF(DAY, CONVERT(DATE, '{$fromDate}'), CONVERT(DATE, LVLEAVEREQ_EDATE)) + 1 WHEN CONVERT(DATE, '{$toDate}') < CONVERT(DATE, LVLEAVEREQ_EDATE) THEN DATEDIFF(DAY, CONVERT(DATE, LVLEAVEREQ_BDATE), CONVERT(DATE, '{$toDate}')) + 1 ELSE DATEDIFF(DAY, CONVERT(DATE, LVLEAVEREQ_BDATE), CONVERT(DATE, LVLEAVEREQ_EDATE)) + 1 END) FROM [PSA66].[dbo].[LVLEAVEREQ] WHERE [LVLEAVEREQ_EMPID] = HREMP_EMPID AND (CONVERT(DATE, LVLEAVEREQ_BDATE) BETWEEN '{$fromDate}' AND '{$toDate}') AND LVLEAVEREQ_LEAVECODE = 'UL' AND LVLEAVEREQ_STATUS NOT IN ('0', '3', '4') ), 0) AS [UL],
            ISNULL((SELECT SUM( CASE WHEN CONVERT(DATE, '{$fromDate}') > CONVERT(DATE, LVLEAVEREQ_BDATE) THEN DATEDIFF(DAY, CONVERT(DATE, '{$fromDate}'), CONVERT(DATE, LVLEAVEREQ_EDATE)) + 1 WHEN CONVERT(DATE, '{$toDate}') < CONVERT(DATE, LVLEAVEREQ_EDATE) THEN DATEDIFF(DAY, CONVERT(DATE, LVLEAVEREQ_BDATE), CONVERT(DATE, '{$toDate}')) + 1 ELSE DATEDIFF(DAY, CONVERT(DATE, LVLEAVEREQ_BDATE), CONVERT(DATE, LVLEAVEREQ_EDATE)) + 1 END) FROM [PSA66].[dbo].[LVLEAVEREQ] WHERE [LVLEAVEREQ_EMPID] = HREMP_EMPID AND (CONVERT(DATE, LVLEAVEREQ_BDATE) BETWEEN '{$fromDate}' AND '{$toDate}') AND LVLEAVEREQ_LEAVECODE = 'WL' AND LVLEAVEREQ_STATUS NOT IN ('0', '3', '4') ), 0) AS [WL],
            ISNULL((SELECT SUM( CASE WHEN CONVERT(DATE, '{$fromDate}') > CONVERT(DATE, LVLEAVEREQ_BDATE) THEN DATEDIFF(DAY, CONVERT(DATE, '{$fromDate}'), CONVERT(DATE, LVLEAVEREQ_EDATE)) + 1 WHEN CONVERT(DATE, '{$toDate}') < CONVERT(DATE, LVLEAVEREQ_EDATE) THEN DATEDIFF(DAY, CONVERT(DATE, LVLEAVEREQ_BDATE), CONVERT(DATE, '{$toDate}')) + 1 ELSE DATEDIFF(DAY, CONVERT(DATE, LVLEAVEREQ_BDATE), CONVERT(DATE, LVLEAVEREQ_EDATE)) + 1 END) FROM [PSA66].[dbo].[LVLEAVEREQ] WHERE [LVLEAVEREQ_EMPID] = HREMP_EMPID AND (CONVERT(DATE, LVLEAVEREQ_BDATE) BETWEEN '{$fromDate}' AND '{$toDate}') AND LVLEAVEREQ_LEAVECODE = 'XL' AND LVLEAVEREQ_STATUS NOT IN ('0', '3', '4') ), 0) AS [XL]
            FROM HREMP emp
            INNER JOIN HRJOB job ON emp.HREMP_JOBID = job.HRJOB_JOBID
            INNER JOIN ASORG org ON emp.HREMP_ORG = org.ASORG_ORGID
            WHERE HREMP_STATUS = 1 AND HREMP_ORG = {$org}
            )

            SELECT *, (cte.AB + cte.AL + cte.FL + cte.HL + cte.ML + cte.NDL + cte.PH + cte.PL + cte.SL + cte.SPL + cte.TL + cte.UL + cte.WL + cte.XL) AS [Total]
            FROM cte
            ORDER BY EmpCode ASC ";

    $stmt = $psa_connect->prepare($sql);
    $stmt->execute();

    $dataArray = array();

    while ($row = $stmt->fetch(PDO::FETCH_ASSOC)) {
        $dataArray[] = $row;
    }

    echo json_encode($dataArray);
} catch (PDOException $e) {
    echo $e->getMessage();
}

$psa_connect = NULL;

